### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by VikashKotharyWork** [cjekel/tindetheus#21]
I can see that you've realised this project as a docker image. Could you add the Dockerfile for this project to the repo?

**Comment by cjekel** [comment]
This is a good idea. I haven't kept the docker image up to date, so I should probably look into auto builds as well.

**Comment by cjekel** [comment]
https://github.com/cjekel/tindetheus/commit/e78510ec2b783e67a9fe6b9166c88f80ff34e7a7

**Comment by cjekel** [comment]
@VikashKothary I added a dockerfile and tried to setup automatic docker builds, but the automatic builds were failing because Docker can't clone with ssh the submodule because I don't have write permission to the original pynder source. I couldn't figure out a way to get docker to clone the tindetheus without ssh.

Then I abandoned this since I thought that building the image yourself with the dockerfile was easy enough.

**Comment by VikashKothary** [comment]
@cjekel Is there a reason you're cloning the git repository as opposed to just using `COPY` to move the files across. If it's done by a CI, you can assume all the fine will be identical to the repo.

Also the submodule can be made to use ssh if you want. It just involves updating the url here. https://github.com/cjekel/tindetheus/blob/325fbbfb2665ace363812a21c63c9cb309396c90/.gitmodules#L3
Using the SSH url `git@github.com:charliewolf/pynder.git` will make it use SSH.

Let me know which you prefer.

**Comment by cjekel** [comment]
Let me see if changing that will get the Docker auto builds working

**Comment by cjekel** [comment]
@VikashKothary Feel free to send a PR for that line in the Dockerfile. Other than this, does everything else seem reasonable?

**Comment by VikashKothary** [comment]
Hi @cjekel, that all sounds good. I'll try and make a PR when I next get some free time. I'll be nice to have the Docker image working again. :+1:

**Comment by cjekel** [comment]
So the Docker autobuilds are working again. 

I changed the submodule to point to https://github.com/cjekel/pynder.git to deal with not having permission from https://github.com/charliewolf/pynder.git which was previously killing the autobuild process. 

I also used ```COPY``` instead of git clone.

Thanks for the help!
